### ISSUE TITLE
Unused variable in GetS1

### ISSUE THREAD

**Issue by riffard** [NESTCollaboration/nest#112]
At the line: https://github.com/NESTCollaboration/nest/blob/master/src/NEST.cpp#L787
there is the definition of the variable `dt` which is never used in `GetS1` scope.

**Comment by mszydagis** [comment]
This was left over from when NEST used drift time (in micro-seconds) instead of (true) Z-position (in mm or cm) to do the S1 position variation and subsequent correction. Good catch, Q, might have been there for years. But now fixed: https://github.com/NESTCollaboration/nest/commit/9217124972c5f20619b62e51b3f29d64ce0aa1f6 so closing issue, @riffard
