### ISSUE TITLE
Verbose level

### ISSUE THREAD

**Issue by riffard** [NESTCollaboration/nest#113]
Is it possible to control the verbose level in NEST using some interger?

**Comment by mszydagis** [comment]
I am closing this after doing https://github.com/NESTCollaboration/nest/commit/9217124972c5f20619b62e51b3f29d64ce0aa1f6 because I think this is good enough: I have not added an integer, but I have added "&& verbosity" to a ton of if-statements on messages, especially in execNEST and rootNEST. This did not help with NEST.cpp however, which does not have access to this flag even; however, I have eliminated the negative number of excitons glitch at high energies of NR (and low) so that message won't come up anymore, and it was what spawned this issue. Moreover, I've added "#define HIGH_E_NR" to NEST.hh to allow it to be raised above 330 keV(nr) thus making the other annoying message go away too.
