### ISSUE TITLE
Consolidate file locations

### ISSUE THREAD

**Issue by tunnell** [NESTCollaboration/nest#6]
When trying to make programs that use the nest library, an issue I encounter is the sporadic location of where header files are located.  Can we do the following:

- G4 bindings move into a new repository
- Examples in their own folder
- NEST and VDetector header in same location
- NEST and VDetector source files in same location

**Comment by tunnell** [comment]
The changes would be:

- Rename Tools to examples
- Create src

- testNEST.cpp -> Tools/
- testSpectra.cpp -> Tools/
- Detectors/DetectorExample_XENON10.hh -> include
- Detectors/VDetector.hh.hh -> include
- NEST.cpp -> src

- G4integration/ -> examples

- Delete empty Detectors

Worth proposing here since it might require people binding to NEST to make changes.  And we'd want to do this once perfectly.  @jpbrodsky @mszydagis

**Comment by jpbrodsky** [comment]
I'd suggest not moving the G4Integration folder, or at least not calling it an example.

The G4 integration code is not intended to be user-modifiable in the way an example should be. Users of the integration should use the classes provided in their G4 code, rather than trying to copy those classes into their project to modify them. This is because the logic required to pipe G4 tracks through the NEST model is complex and has tons of fiddly cases that break easily.

The G4 integration code is also not a ready-to-run example. It requires an existing G4 Monte Carlo to be added into.

**Comment by mszydagis** [comment]
@tunnell  I have collected solid feedback from everyone. And we would like to make the following modifications to your plan. I have composed an average compromise over everyone's ideas:

Rename Tools to examples: OK

Create src:  OK 

testNEST.cpp -> Tools/   No, into src instead please. 

testSpectra.cpp -> Tools/   Is this a typo?? Did you mean into examples/ since renamed above?

Detectors/DetectorExample_XENON10.hh -> include  Not quite: include/Detector

Detectors/VDetector.hh.hh -> include:   Again:  include/Detector 

NEST.cpp -> src:   OK 

G4integration/ -> examples:  @jpbrodsky had said please no, so let's respect that. 

Delete empty Detectors -- see above: preserve as its own subdirectory. 

One more request, from LZ software expert L. Kreczko:  include/*.hh -> include/NEST/ (so, then detector stuff will be in include/Detector in parallel, thus include folder itself will now be empty)

I can speak for LUX and LZ, and if Jason can speak for EXO-200/nEXO and you Chris for XENON1T/nT then all stakeholders have agreed. Please proceed and prepare these changes. Everyone agreed though: never again :)  So, it's a case of speak now or forever hold peace..
