### ISSUE TITLE
Truncated gaussian

### ISSUE THREAD

**Issue by riffard** [NESTCollaboration/nest#83]
In NEST, the size of photo-electron is drawn from a Gaussian with allow negative value for the pulse area of SPE. It needs to be changed by a truncated gaussian to avoid negative values.

**Comment by mszydagis** [comment]
@riffard , https://github.com/NESTCollaboration/nest/commit/2093f966d70ef51ff63b47b649e7210f5b4a7b2a  Should have this problem solved now. I did not neglect the 2-PE effect either: both the variables phe1 and phe2 have been changed. Even though I have already pushed to master (after triple-checking however that no ill effects, using LUX Run03 D-D band as test case since NRs are disproportionately affected having the lowest-energy signals of course in S1) please look over and verify that you like my changes, even though I have also closed the issue already now (I can always reopen of course, if need be). I also checked that, sans noiseB[0] and [1] (i.e. both set to 0) and after removal of all phe's of value 0.000 the phe1 (didn't check phe2, but should be identical) distribution has a mean of 1.0000... to very high precision after millions of events. (Trying to tag Aaron M. too, but can't find him as user...)
